### ISSUE TITLE
My script  is named main.py

### ISSUE THREAD

**Issue by Vampirebat** [say4n/hotreload#1]
when i run this program, it tries to start the app (kivy app)
but the screen never loads...

i try to use the full path of my py file

but it says ModuleNotFoundError: No module named '/run/media/vampyre/Projects/thoughtcloudbuild/main'

i add the .py to the end of script =

import time
import logging
from hotreload import Loader

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    
    script = Loader("/run/media/vampyre/Projects/thoughtcloudbuild/main.py")

    while True:
        # Check if script has been modified since last poll.
        if script.has_changed():
            # Execute a function from script if it has been modified.
            script.start()
        time.sleep(1)

is it because my file is named main?

**Comment by rttomlinson** [comment]
hey @Vampirebat, I'm not the author nor a python expert and I just happened to come across this library. I think the issue you're running in to is related to this line https://github.com/say4n/hotreload/blob/master/hotreload/reloader.py#L35. `splitext` just splits on the filename and the extension. In your case, `/run/media/vampyre/Projects/thoughtcloudbuild/main` is not the name of a module in your python path (as it probably shouldn't be). I believe this library just assumes you'll be running it from the root directory of your project. Hope this helps.
